import CLCMetatronAdapter.CertificateProvenance
import CLCMetatronAdapter.CertificateProvenanceTest

#print axioms CLCMetatronAdapter.certificateProvenanceSupport
#print axioms CLCMetatronAdapter.certificateProvenance_verifiedTransport_static_authority
#print axioms CLCMetatronAdapter.certificateProvenance_verifiedTransport_decisive_preserved
#print axioms CLCMetatronAdapter.unit_certificate_provenance_not_unique
#print axioms CLCMetatronAdapter.unit_certificate_identity_does_not_determine_warrant
#print axioms CLCMetatronAdapter.unit_identity_transport_preserved_with_bound_provenance
