import CLCMetatronAdapter.LiveWarrantCertificate
import CLCMetatronAdapter.LiveWarrantCertificateTest

#print axioms CLCMetatronAdapter.liveWarrantCertificate_exists_iff
#print axioms CLCMetatronAdapter.liveWarrantCertificateSupport
#print axioms CLCMetatronAdapter.liveWarrantCertificate_verifiedTransport_static_authority
#print axioms CLCMetatronAdapter.liveWarrantCertificate_verifiedTransport_decisive_preserved
#print axioms CLCMetatronAdapter.singleton_id_transport_preserves_decisive_with_earned_support
#print axioms CLCMetatronAdapter.revoked_fixture_has_no_certificate_one
