import Metatron.CausalTraceQuotient

namespace Metatron.FinitePosetConnectivity

open Metatron.CausalLinearization
open Metatron.CausalTraceQuotient
open Metatron.CausalRepairCover
open Metatron.PortEventStructure
open Metatron.FutureObservations

universe u v

def Incomparable
    {E : Type u}
    (R : E → E → Prop)
    (a b : E) : Prop :=
  (¬ R a b) ∧ (¬ R b a)

/--
A duplicate-free finite topological schedule. At each head event, no event
remaining in the tail is required to precede it.
-/
def Topo
    {E : Type u}
    (R : E → E → Prop) : List E → Prop
  | [] => True
  | x :: xs =>
      x ∉ xs ∧
      (∀ y, y ∈ xs → ¬ R y x) ∧
      Topo R xs

/--
Purely combinatorial trace generated by adjacent swaps of incomparable events.
-/
inductive PosetTrace
    {E : Type u}
    (R : E → E → Prop) :
    List E → List E → Prop
  | refl (xs : List E) :
      PosetTrace R xs xs
  | swap
      (pre post : List E)
      (a b : E)
      (hinc : Incomparable R a b) :
      PosetTrace R
        (pre ++ a :: b :: post)
        (pre ++ b :: a :: post)
  | symm
      {xs ys : List E}
      (h : PosetTrace R xs ys) :
      PosetTrace R ys xs
  | trans
      {xs ys zs : List E}
      (hxy : PosetTrace R xs ys)
      (hyz : PosetTrace R ys zs) :
      PosetTrace R xs zs

theorem posetTrace_cons
    {E : Type u}
    {R : E → E → Prop}
    (x : E)
    {xs ys : List E}
    (h : PosetTrace R xs ys) :
    PosetTrace R (x :: xs) (x :: ys) := by
  induction h with
  | refl xs =>
      exact PosetTrace.refl _
  | swap pre post a b hinc =>
      simpa using
        PosetTrace.swap (R := R) (x :: pre) post a b hinc
  | symm h ih =>
      exact PosetTrace.symm ih
  | trans hxy hyz ihxy ihyz =>
      exact PosetTrace.trans ihxy ihyz

theorem topo_remove_middle
    {E : Type u}
    {R : E → E → Prop}
    (pre post : List E)
    (x : E)
    (h : Topo R (pre ++ x :: post)) :
    Topo R (pre ++ post) := by
  induction pre with
  | nil =>
      change Topo R (x :: post) at h
      change Topo R post
      exact h.2.2
  | cons y pre ih =>
      change Topo R (y :: (pre ++ x :: post)) at h
      change Topo R (y :: (pre ++ post))
      refine ⟨?_, ?_, ih h.2.2⟩
      · intro hy
        apply h.1
        simp only [List.mem_append, List.mem_cons]
        simp only [List.mem_append] at hy
        cases hy with
        | inl hp =>
            exact Or.inl hp
        | inr hpost =>
            exact Or.inr (Or.inr hpost)
      · intro z hz
        apply h.2.1 z
        simp only [List.mem_append, List.mem_cons]
        simp only [List.mem_append] at hz
        cases hz with
        | inl hp =>
            exact Or.inl hp
        | inr hpost =>
            exact Or.inr (Or.inr hpost)

theorem topo_prefix_not_reverse
    {E : Type u}
    {R : E → E → Prop}
    (pre post : List E)
    (x : E)
    (h : Topo R (pre ++ x :: post)) :
    ∀ y, y ∈ pre → ¬ R x y := by
  induction pre with
  | nil =>
      intro y hy
      cases hy
  | cons y pre ih =>
      change Topo R (y :: (pre ++ x :: post)) at h
      intro z hz
      simp only [List.mem_cons] at hz
      cases hz with
      | inl hzy =>
          subst z
          apply h.2.1 x
          simp
      | inr hzpre =>
          exact ih h.2.2 z hzpre

theorem bubble_left_by_incomparables
    {E : Type u}
    {R : E → E → Prop}
    (pre post : List E)
    (x : E)
    (hinc : ∀ y, y ∈ pre → Incomparable R y x) :
    PosetTrace R
      (pre ++ x :: post)
      (x :: (pre ++ post)) := by
  induction pre with
  | nil =>
      simpa using PosetTrace.refl (R := R) (x :: post)
  | cons y pre ih =>
      have htail :
          ∀ z, z ∈ pre → Incomparable R z x := by
        intro z hz
        exact hinc z (by simp [hz])
      have h1 :
          PosetTrace R
            (y :: (pre ++ x :: post))
            (y :: x :: (pre ++ post)) := by
        simpa using posetTrace_cons y (ih htail)
      have hyx : Incomparable R y x :=
        hinc y (by simp)
      have h2 :
          PosetTrace R
            (y :: x :: (pre ++ post))
            (x :: y :: (pre ++ post)) := by
        simpa using
          PosetTrace.swap (R := R) [] (pre ++ post) y x hyx
      exact PosetTrace.trans h1 h2

/--
Any two duplicate-free topological schedules of the same finite event multiset
are connected by adjacent swaps of incomparable events.
-/
theorem all_topological_sorts_traceConnected
    {E : Type u}
    {R : E → E → Prop}
    {xs ys : List E}
    (hx : Topo R xs)
    (hy : Topo R ys)
    (hp : xs.Perm ys) :
    PosetTrace R xs ys := by
  induction xs generalizing ys with
  | nil =>
      have hnil : ys = [] := List.nil_perm.mp hp
      subst ys
      exact PosetTrace.refl _
  | cons x xs ih =>
      change
        x ∉ xs ∧
        (∀ y, y ∈ xs → ¬ R y x) ∧
        Topo R xs at hx
      rcases hx with ⟨hxnot, hxhead, hxtail⟩
      have hxmem : x ∈ ys :=
        hp.subset (by simp)
      obtain ⟨pre, post, hys⟩ := List.append_of_mem hxmem
      subst ys
      have hpTail : xs.Perm (pre ++ post) := by
        exact (hp.trans List.perm_middle).cons_inv
      have hyRemoved : Topo R (pre ++ post) :=
        topo_remove_middle pre post x hy
      have hprefixReverse :
          ∀ y, y ∈ pre → ¬ R x y :=
        topo_prefix_not_reverse pre post x hy
      have hinc :
          ∀ y, y ∈ pre → Incomparable R y x := by
        intro y hypre
        constructor
        · apply hxhead y
          apply hpTail.mem_iff.mpr
          simp [hypre]
        · exact hprefixReverse y hypre
      have hbubble :
          PosetTrace R
            (pre ++ x :: post)
            (x :: (pre ++ post)) :=
        bubble_left_by_incomparables pre post x hinc
      have hrec :
          PosetTrace R xs (pre ++ post) :=
        ih hxtail hyRemoved hpTail
      have hcons :
          PosetTrace R
            (x :: xs)
            (x :: (pre ++ post)) :=
        posetTrace_cons x hrec
      exact PosetTrace.trans hcons (PosetTrace.symm hbubble)

/--
Map a purely combinatorial incomparable-event trace to the already-qualified
semantic trace whenever every incomparable pair is certified to commute.
-/
theorem posetTrace_to_semanticTrace
    {E : Type u} {State : Type v} {Gen : Type}
    {R : E → E → Prop}
    (act : Gen → State → State)
    (label : E → Gen)
    (hcomm :
      ∀ a b,
        Incomparable R a b →
          Commute act (label a) (label b))
    {xs ys : List E}
    (htrace : PosetTrace R xs ys) :
    TraceEq act (xs.map label) (ys.map label) := by
  induction htrace with
  | refl xs =>
      exact TraceEq.refl _
  | swap pre post a b hinc =>
      simpa [List.map_append] using
        TraceEq.swap (act := act)
          (pre.map label) (post.map label)
          (label a) (label b)
          (hcomm a b hinc)
  | symm h ih =>
      exact TraceEq.symm ih
  | trans hxy hyz ihxy ihyz =>
      exact TraceEq.trans ihxy ihyz

theorem all_topological_sorts_semantically_invariant
    {E : Type u} {State : Type v} {Gen : Type}
    {R : E → E → Prop}
    (act : Gen → State → State)
    (label : E → Gen)
    (hcomm :
      ∀ a b,
        Incomparable R a b →
          Commute act (label a) (label b))
    {xs ys : List E}
    (hx : Topo R xs)
    (hy : Topo R ys)
    (hp : xs.Perm ys) :
    ∀ s,
      run act (xs.map label) s =
        run act (ys.map label) s := by
  have hposet :
      PosetTrace R xs ys :=
    all_topological_sorts_traceConnected hx hy hp
  have hsemantic :
      TraceEq act (xs.map label) (ys.map label) :=
    posetTrace_to_semanticTrace act label hcomm hposet
  exact traceEq_preserves_run act hsemantic

def PESBefore
    {E : Type u}
    (p : PES E) (a b : E) : Prop :=
  p.beforeB a b = true

def TopologicalSchedule
    {E : Type u}
    (p : PES E)
    (xs : List E) : Prop :=
  Topo (PESBefore p) xs ∧ xs.Perm p.events

theorem pes_topological_sorts_traceConnected
    {E : Type u}
    (p : PES E)
    {xs ys : List E}
    (hx : TopologicalSchedule p xs)
    (hy : TopologicalSchedule p ys) :
    PosetTrace (PESBefore p) xs ys := by
  apply all_topological_sorts_traceConnected
    hx.1 hy.1
  exact hx.2.trans hy.2.symm

theorem pes_all_topological_sorts_semantically_invariant
    {E : Type u} {State : Type v} {Gen : Type}
    (p : PES E)
    (act : Gen → State → State)
    (label : E → Gen)
    (hcomm :
      ∀ a b,
        Incomparable (PESBefore p) a b →
          Commute act (label a) (label b))
    {xs ys : List E}
    (hx : TopologicalSchedule p xs)
    (hy : TopologicalSchedule p ys) :
    ∀ s,
      run act (xs.map label) s =
        run act (ys.map label) s := by
  have hp : xs.Perm ys :=
    hx.2.trans hy.2.symm
  exact all_topological_sorts_semantically_invariant
    act label hcomm hx.1 hy.1 hp

/-! A nontrivial finite-poset fixture: 0 and 1 are incomparable, both before 2. -/

def forkRelation (a b : Nat) : Prop :=
  (a = 0 ∧ b = 2) ∨
  (a = 1 ∧ b = 2)

def forkA : List Nat := [0, 1, 2]
def forkB : List Nat := [1, 0, 2]

theorem forkA_topological :
    Topo forkRelation forkA := by
  simp [forkA, Topo, forkRelation]

theorem forkB_topological :
    Topo forkRelation forkB := by
  simp [forkB, Topo, forkRelation]

theorem fork_permutation :
    forkA.Perm forkB := by
  simpa [forkA, forkB] using
    (List.Perm.swap 0 1 [2]).symm

theorem fork_topological_sorts_connected :
    PosetTrace forkRelation forkA forkB :=
  all_topological_sorts_traceConnected
    forkA_topological forkB_topological fork_permutation

/-! Negative retention: comparable events cannot be crossed by the trace generator. -/

def chainRelation (a b : Nat) : Prop :=
  a = 0 ∧ b = 1

theorem chain_not_incomparable :
    ¬ Incomparable chainRelation 0 1 := by
  intro h
  exact h.1 (by simp [chainRelation])

end Metatron.FinitePosetConnectivity
