namespace Metatron.OrientationStabilizer

inductive Symmetry where
  | identity
  | reflection
  | reversal
  | compound
  deriving DecidableEq, Repr

/-- Two independent orientation bits:
    the first tracks glyph reflection; the second tracks reading-order reversal. -/
abbrev OrientationState := Bool × Bool

/-- The minimal coherence predicate extracted from the source prose:
    glyph orientation and reading direction agree. -/
def Coherent (s : OrientationState) : Prop :=
  s.1 = s.2

def act : Symmetry → OrientationState → OrientationState
  | .identity, s => s
  | .reflection, s => (!s.1, s.2)
  | .reversal, s => (s.1, !s.2)
  | .compound, s => (!s.1, !s.2)

def PreservesCoherence (g : Symmetry) : Prop :=
  ∀ s, Coherent s → Coherent (act g s)

theorem identity_preserves :
    PreservesCoherence .identity := by
  intro s hs
  exact hs

theorem compound_preserves :
    PreservesCoherence .compound := by
  intro s hs
  exact congrArg (fun b : Bool => !b) hs

theorem reflection_does_not_preserve :
    ¬ PreservesCoherence .reflection := by
  intro h
  have hbad := h (false, false) rfl
  simp [Coherent, act] at hbad

theorem reversal_does_not_preserve :
    ¬ PreservesCoherence .reversal := by
  intro h
  have hbad := h (false, false) rfl
  simp [Coherent, act] at hbad

theorem reflection_reversal_commute (s : OrientationState) :
    act .reflection (act .reversal s) =
      act .reversal (act .reflection s) := by
  cases s
  rfl

theorem compound_eq_reflection_after_reversal (s : OrientationState) :
    act .compound s = act .reflection (act .reversal s) := by
  cases s
  rfl

/-- Exact stabilizer of the declared orientation-coherence predicate
    inside the four transformations generated by the two involutions. -/
theorem stabilizer_exact (g : Symmetry) :
    PreservesCoherence g ↔
      g = .identity ∨ g = .compound := by
  constructor
  · intro hp
    cases g with
    | identity =>
        exact Or.inl rfl
    | reflection =>
        exact (reflection_does_not_preserve hp).elim
    | reversal =>
        exact (reversal_does_not_preserve hp).elim
    | compound =>
        exact Or.inr rfl
  · intro hg
    rcases hg with h | h
    · subst g
      exact identity_preserves
    · subst g
      exact compound_preserves

theorem only_nontrivial_preserver_is_compound
    (g : Symmetry)
    (hp : PreservesCoherence g)
    (hne : g ≠ .identity) :
    g = .compound := by
  rcases (stabilizer_exact g).1 hp with h | h
  · exact (hne h).elim
  · exact h

end Metatron.OrientationStabilizer
