import Metatron.ResidualBasis

namespace Metatron.ResidualInteractions

open Metatron.ResidualBasis

universe u v

abbrev Relation (State : Type u) := State → State → Prop

/--
A general, possibly synergistic refinement semantics.

`generatedSeparates basis x y` means the whole installed basis, after lawful
closure/composition, can distinguish x from y. It need not decompose into the
union of effects contributed by singleton generators.
-/
def GeneratedRefinedBy
    {State : Type u} {Candidate : Type v}
    (current : Relation State)
    (generatedSeparates : List Candidate → State → State → Prop)
    (basis : List Candidate) : Relation State :=
  fun x y =>
    current x y ∧ ¬ generatedSeparates basis x y

def GeneratedCoversResidual
    {State : Type u} {Candidate : Type v}
    (current target : Relation State)
    (generatedSeparates : List Candidate → State → State → Prop)
    (basis : List Candidate) : Prop :=
  ∀ x y,
    ResidualPair current target x y →
      generatedSeparates basis x y

def GeneratedTargetSufficient
    {State : Type u} {Candidate : Type v}
    (current target : Relation State)
    (generatedSeparates : List Candidate → State → State → Prop)
    (basis : List Candidate) : Prop :=
  ∀ x y,
    GeneratedRefinedBy current generatedSeparates basis x y →
      target x y

/--
The residual/sufficiency bridge does not require additivity.

What changes in the synergistic setting is the object whose coverage is
computed: it must be the distinction generated by the whole candidate family
after closure, rather than a union of singleton hyperedges.
-/
theorem generatedResidualBasis_closes
    {State : Type u} {Candidate : Type v}
    (current target : Relation State)
    (generatedSeparates : List Candidate → State → State → Prop)
    (basis : List Candidate) :
    GeneratedCoversResidual current target generatedSeparates basis ↔
      GeneratedTargetSufficient current target generatedSeparates basis := by
  constructor
  · intro hcover x y hrefined
    apply Classical.byContradiction
    intro htarget
    have hres : ResidualPair current target x y :=
      ⟨hrefined.1, htarget⟩
    exact hrefined.2 (hcover x y hres)
  · intro hsufficient x y hres
    apply Classical.byContradiction
    intro hnot
    have hrefined :
        GeneratedRefinedBy current generatedSeparates basis x y :=
      ⟨hres.1, hnot⟩
    exact hres.2 (hsufficient x y hrefined)

def MinimumGeneratedCoverByLength
    {State : Type u} {Candidate : Type v}
    (current target : Relation State)
    (generatedSeparates : List Candidate → State → State → Prop)
    (basis : List Candidate) : Prop :=
  GeneratedCoversResidual current target generatedSeparates basis ∧
    ∀ other : List Candidate,
      other.length < basis.length →
        ¬ GeneratedCoversResidual current target generatedSeparates other

theorem minimumGeneratedBasis_minimalSufficient
    {State : Type u} {Candidate : Type v}
    (current target : Relation State)
    (generatedSeparates : List Candidate → State → State → Prop)
    (basis : List Candidate)
    (hmin :
      MinimumGeneratedCoverByLength
        current target generatedSeparates basis) :
    GeneratedTargetSufficient current target generatedSeparates basis ∧
      ∀ other : List Candidate,
        other.length < basis.length →
          ¬ GeneratedTargetSufficient
            current target generatedSeparates other := by
  constructor
  · exact
      (generatedResidualBasis_closes
        current target generatedSeparates basis).1 hmin.1
  · intro other hlt hsufficient
    exact hmin.2 other hlt
      ((generatedResidualBasis_closes
        current target generatedSeparates other).2 hsufficient)

/--
The old singleton-hypergraph semantics is the additive special case: the whole
basis separates a pair exactly when one selected candidate separates it.
-/
def AtomicGenerated
    {State : Type u} {Candidate : Type v}
    (separates : Candidate → State → State → Prop)
    (basis : List Candidate)
    (x y : State) : Prop :=
  ∃ g, g ∈ basis ∧ separates g x y

theorem atomicGenerated_cover_iff
    {State : Type u} {Candidate : Type v}
    (current target : Relation State)
    (separates : Candidate → State → State → Prop)
    (basis : List Candidate) :
    GeneratedCoversResidual
      current target (AtomicGenerated separates) basis ↔
    CoversResidual current target separates basis := by
  rfl

theorem atomicGenerated_sufficient_iff
    {State : Type u} {Candidate : Type v}
    (current target : Relation State)
    (separates : Candidate → State → State → Prop)
    (basis : List Candidate) :
    GeneratedTargetSufficient
      current target (AtomicGenerated separates) basis ↔
    TargetSufficient current target separates basis := by
  constructor
  · intro h x y hrefined
    apply h x y
    constructor
    · exact hrefined.1
    · intro hsep
      rcases hsep with ⟨g, hg, hxy⟩
      exact (hrefined.2 g hg) hxy
  · intro h x y hrefined
    apply h x y
    constructor
    · exact hrefined.1
    · intro g hg hxy
      exact hrefined.2 ⟨g, hg, hxy⟩

/-!
RED-first synergy fixture.

Neither generator distinguishes Bool states alone. Installed together, however,
they enable a derived distinction. This is the smallest witness that singleton
hyperedge union is incomplete once closure can create genuinely joint effects.
-/

inductive SynGen
  | left
  | right
  deriving DecidableEq

def synCurrent : Relation Bool := fun _ _ => True

def synTarget : Relation Bool := fun x y => x = y

/-- No singleton candidate has any direct separating effect. -/
def synAtomicSeparates (_ : SynGen) (_ _ : Bool) : Prop := False

def hasLeft (basis : List SynGen) : Prop :=
  SynGen.left ∈ basis

def hasRight (basis : List SynGen) : Prop :=
  SynGen.right ∈ basis

/--
The joint capability appears only when both generators are installed. This
models a lawful closure/composition consequence unavailable to either member
alone.
-/
def synGeneratedSeparates
    (basis : List SynGen)
    (x y : Bool) : Prop :=
  hasLeft basis ∧ hasRight basis ∧ x ≠ y

theorem synergy_atomic_hypergraph_fails :
    ¬ CoversResidual
      synCurrent synTarget synAtomicSeparates
      [SynGen.left, SynGen.right] := by
  intro h
  have hres : ResidualPair synCurrent synTarget false true := by
    exact ⟨trivial, by decide⟩
  rcases h false true hres with ⟨g, hg, hsep⟩
  exact hsep

theorem synergy_pair_generated_covers :
    GeneratedCoversResidual
      synCurrent synTarget synGeneratedSeparates
      [SynGen.left, SynGen.right] := by
  intro x y hres
  exact ⟨by simp [hasLeft], by simp [hasRight], hres.2⟩

theorem synergy_pair_target_sufficient :
    GeneratedTargetSufficient
      synCurrent synTarget synGeneratedSeparates
      [SynGen.left, SynGen.right] :=
  (generatedResidualBasis_closes
    synCurrent synTarget synGeneratedSeparates
    [SynGen.left, SynGen.right]).1
    synergy_pair_generated_covers

theorem synergy_left_alone_fails :
    ¬ GeneratedTargetSufficient
      synCurrent synTarget synGeneratedSeparates
      [SynGen.left] := by
  intro h
  have hrefined :
      GeneratedRefinedBy
        synCurrent synGeneratedSeparates [SynGen.left]
        false true := by
    constructor
    · trivial
    · intro hsep
      exact (by
        have hr : hasRight [SynGen.left] := hsep.2.1
        simpa [hasRight] using hr)
  have hbad : false = true := h false true hrefined
  cases hbad

theorem synergy_right_alone_fails :
    ¬ GeneratedTargetSufficient
      synCurrent synTarget synGeneratedSeparates
      [SynGen.right] := by
  intro h
  have hrefined :
      GeneratedRefinedBy
        synCurrent synGeneratedSeparates [SynGen.right]
        false true := by
    constructor
    · trivial
    · intro hsep
      exact (by
        have hl : hasLeft [SynGen.right] := hsep.1
        simpa [hasLeft] using hl)
  have hbad : false = true := h false true hrefined
  cases hbad

theorem synergy_empty_fails :
    ¬ GeneratedTargetSufficient
      synCurrent synTarget synGeneratedSeparates [] := by
  intro h
  have hrefined :
      GeneratedRefinedBy
        synCurrent synGeneratedSeparates []
        false true := by
    constructor
    · trivial
    · intro hsep
      have hl : hasLeft [] := hsep.1
      simpa [hasLeft] using hl
  have hbad : false = true := h false true hrefined
  cases hbad

theorem synergy_pair_is_minimum_generated_basis :
    MinimumGeneratedCoverByLength
      synCurrent synTarget synGeneratedSeparates
      [SynGen.left, SynGen.right] := by
  constructor
  · exact synergy_pair_generated_covers
  · intro other hlt
    intro hcover
    have hres : ResidualPair synCurrent synTarget false true := by
      exact ⟨trivial, by decide⟩
    have hsep := hcover false true hres
    have hl : SynGen.left ∈ other := hsep.1
    have hr : SynGen.right ∈ other := hsep.2.1
    cases other with
    | nil =>
        simpa using hl
    | cons a tail =>
        cases tail with
        | nil =>
            cases a with
            | left =>
                simpa using hr
            | right =>
                simpa using hl
        | cons b rest =>
            have hge : 2 ≤ (a :: b :: rest).length := by
              simp
            exact (Nat.not_lt_of_ge hge) hlt

theorem synergy_minimum_target_sufficient :
    GeneratedTargetSufficient
      synCurrent synTarget synGeneratedSeparates
      [SynGen.left, SynGen.right] ∧
    ∀ other : List SynGen,
      other.length < 2 →
        ¬ GeneratedTargetSufficient
          synCurrent synTarget synGeneratedSeparates other := by
  exact
    minimumGeneratedBasis_minimalSufficient
      synCurrent synTarget synGeneratedSeparates
      [SynGen.left, SynGen.right]
      synergy_pair_is_minimum_generated_basis

end Metatron.ResidualInteractions
